"""create tables

Revision ID: c8555b3c6cae
Revises: 
Create Date: 2026-04-30 23:38:59.966658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8555b3c6cae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student', sa.String(length=100), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('competency', sa.String(length=20), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('construct', sa.String(length=100), nullable=True),
    sa.Column('bloom', sa.Float(), nullable=True),
    sa.Column('dok', sa.Float(), nullable=True),
    sa.Column('readability', sa.Float(), nullable=True),
    sa.Column('avg_sentence_length', sa.Float(), nullable=True),
    sa.Column('feature_vector', sa.Text(), nullable=True),
    sa.Column('cluster', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    # ### end Alembic commands ###
